[package]
name = "BinaryBetting"
version = "1.0.0"
authors = ["Orion Team"]

[addresses]
binary_betting = "_"

[dev-addresses]
binary_betting = "0x1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
